#!/bin/sh
PATH=/usr/local/bin:/usr/local/sbin:~/bin:/usr/bin:/bin:/usr/sbin:/sbin
cd /Users/$(id -un)/Pictures/unsplash-wallpapers
ls |sort -R |tail -$N |while read file; do
    echo pwd
    /usr/local/bin/wallpaper /Users/$(id -un)/Pictures/unsplash-wallpapers/$file fill
done
cd /