#!/bin/sh
PATH=/usr/local/bin:/usr/local/sbin:~/bin:/usr/bin:/bin:/usr/sbin:/sbin
if [[ -z "$1" ]]; then
    curl -L -s --compressed "https://source.unsplash.com/1920x1080/daily" -o /Users/$(id -un)/Pictures/unsplash-wallpapers/`date +"%s"`.jpg
else
    curl -L -s --compressed "https://source.unsplash.com/1920x1080/?$1" -o /Users/$(id -un)/Pictures/unsplash-wallpapers/`date +"%s"`.jpg
fi

ls -tr /Users/$(id -un)/Pictures/unsplash-wallpapers/*.jpg|tail -n 1 |while read file; do
    /usr/local/bin/wallpaper $file fill
done